### ISSUE TITLE
All string variables end with \x00

### ISSUE THREAD

**Issue by Vinno97** [bahorn/OpenRGB-PyClient#1]
Hi,

First of all, thanks for this library! It's amazing how quickly you put it together, and without it I wouldn't have been able to develop my own app nearly as quickly. (still in development, not yet publicly available)

Secondly: I did find that all strings from the API end with an escaped null character. I think you may have forgotten to strip these away. 

As an example, here I've printed some properties from my Wraith Prism cooler
![image](https://user-images.githubusercontent.com/9059378/82766341-95f09180-9e1e-11ea-9b80-aeba59c3281a.png)

**Comment by bahorn** [comment]
Should hopefully be resolved now! And yep, was something I forgot to do
